apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: eu.gcr.io/blackalert-207710/mongodb
        ports:
        - containerPort: 27017
